name: CI-CD-Shopme-Process

on:
  push:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci_part: 
  #build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: npm run production
