name: CI-CD-Shopme-Process

on:
  push:
    branches: 
      - main


jobs:
  ci_part: 
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repo
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: npm run production
